import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "../lib/registry";
import localFont from 'next/font/local'

const myFont = localFont({ src: './fonts/Moon2.0-Regular.otf' })



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ fontFamily: myFont.style.fontFamily }}>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
